const API="/api";let token=localStorage.getItem("token")||"";let cu=null;let curRest=null;let curQty={};
function toast(m){const t=document.createElement("div");t.className="toast";t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
async function api(p,o={}){const h={"Content-Type":"application/json"};if(token)h["Authorization"]="Bearer "+token;const r=await fetch(API+p,{...o,headers:h});const d=await r.json();if(!r.ok)throw new Error(d.error||"请求失败");return d}
function showPage(p){document.querySelectorAll(".page").forEach(e=>e.classList.remove("active"));const el=document.getElementById("page-"+p);if(el)el.classList.add("active");const nav=document.querySelector(".btm-nav");if(!nav)return;nav.style.display=["rest","search"].includes(p)?"none":"flex";if(p==="home"){loadRests();updBdg()}else if(p==="cart-page"){loadCart()}else if(p==="orders-page"){loadOrders()}else if(p==="profile-page"){loadProfile()}}
function switchAuth(v){document.querySelectorAll(".atab").forEach(e=>e.classList.remove("active"));document.querySelectorAll(".aform").forEach(e=>e.classList.remove("active"));if(v){document.querySelector(".atab:first-child").classList.add("active");document.getElementById("f-login").classList.add("active")}else{document.querySelector(".atab:last-child").classList.add("active");document.getElementById("f-reg").classList.add("active")}}
async function handleLogin(e){e.preventDefault();const inp=e.target.querySelectorAll("input");try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({username:inp[0].value,password:inp[1].value})});token=d.token;cu=d.user;localStorage.setItem("token",token);toast("登录成功！");document.getElementById("page-auth").classList.remove("active");document.getElementById("page-home").classList.add("active");loadRests();updBdg()}catch(e){toast(e.message||"用户名或密码错误")}}
async function handleRegister(e){e.preventDefault();const inp=e.target.querySelectorAll("input");if(inp[2].value!==inp[3].value)return toast("两次密码不一致");try{const d=await api("/auth/register",{method:"POST",body:JSON.stringify({username:inp[0].value,phone:inp[1].value,password:inp[2].value})});token=d.token;cu=d.user;localStorage.setItem("token",token);toast("注册成功！");document.getElementById("page-auth").classList.remove("active");document.getElementById("page-home").classList.add("active");loadRests();updBdg()}catch(e){toast(e.message||"注册失败")}}
function handleLogout(){if(!confirm("确认退出？"))return;token="";cu=null;localStorage.removeItem("token");document.querySelectorAll(".page").forEach(e=>e.classList.remove("active"));document.getElementById("page-auth").classList.add("active");switchAuth(1)}
async function loadRests(){const feed=document.getElementById("feed");try{const d=await api("/restaurants");if(!d.length){feed.innerHTML='<div class="empty"><p>暂无商家</p></div>';return}const cats=[...new Set(d.map(r=>r.category))];const bar=document.getElementById("cat-bar");const em={"食堂快餐":"🍚","川菜":"🌶️","茶餐厅":"🍵","小吃快餐":"🍟","面食":"🍜","韩餐":"🇰🇷","早餐":"🥟"};let ch='<div class="cat-item active" data-c=""><div class="ci" style="background:#FF6B6B">🍽️</div><span>全部</span></div>';cats.forEach(c=>{ch+=`<div class="cat-item" data-c="${c}"><div class="ci" style="background:#FF8C5A">${em[c]||"🍽️"}</div><span>${c}</span></div>`});bar.innerHTML=ch;bar.querySelectorAll(".cat-item").forEach(el=>{el.onclick=()=>{bar.querySelectorAll(".cat-item").forEach(x=>x.classList.remove("active"));el.classList.add("active");const c=el.dataset.c;if(!c)loadRests();else api("/restaurants?category="+encodeURIComponent(c)).then(x=>renderR(x))}});renderR(d)}catch{feed.innerHTML='<div class="empty"><p>加载失败</p></div>'}}
function renderR(rests,container){const em=["🍚","🌶️","🍵","🍗","🍜","🇰🇷","🌶️","🥟"];(container||document.getElementById("feed")).innerHTML=rests.map(r=>`<div class="rcard" onclick="openRest(${r.id})"><div class="rimg">${em[(r.id-1)%8]}</div><div class="rdetail"><h4>${r.name}</h4><div class="desc">${r.description||""}</div><div class="rtags"><span class="tag">${r.category}</span>${r.deliveryFee==0?'<span class="tag" style="background:#E8F5E9;color:#4CAF50">免配送费</span>':""}</div><div class="rstats"><span class="rating">★ ${r.rating}</span><span>月售${r.sales}</span><span>配送费¥${r.deliveryFee}</span></div></div></div>`).join("")}

// === 商家 ===
async function openRest(id){const d=await api("/restaurants/"+id);curRest=d;document.getElementById("rname").textContent=d.name;document.getElementById("rmeta").innerHTML=`★ ${d.rating} 月售${d.sales} ｜ 配送费¥${d.deliveryFee}`;if(token){try{const ci=await api("/cart");const cq={};ci.filter(x=>x.restaurantId===id).forEach(x=>{cq[x.menuItemId]=x.quantity});curQty[id]=cq}catch{}}renderMenu(d.menu);updFC();showPage("rest")}
function renderMenu(items){const cats=[...new Set(items.map(i=>i.category||"其他"))];const me={"红烧肉":"🥩","排骨":"🥩","鸡":"🍗","鱼":"🐟","牛肉":"🥩","面":"🍜","肠粉":"🥟","蛋":"🥚","奶茶":"🧋","汤":"🥣","粥":"🥣","饭":"🍚","香锅":"🥘","炸鸡":"🍗","泡菜":"🥬","年糕":"🍡","冰粉":"🧊","豆浆":"🥛"};const ge=n=>{for(const[k,v]of Object.entries(me))if(n.includes(k))return v;return"🍽️"};document.getElementById("menu-wrap").innerHTML=cats.map(c=>{const ci=items.filter(i=>(i.category||"其他")===c);const qm=curQty[curRest?.id]||{};return`<div class="mcat"><h5>${c}</h5>${ci.map(i=>{const q=qm[i.id]||0;return`<div class="mitem"><div class="mimg">${ge(i.name)}</div><div class="minfo"><h6>${i.name}</h6><div class="mdesc">${i.description||""}</div><div class="msales">月售${i.sales}</div></div><div class="mright"><div><span class="mprice">¥${i.price}</span>${i.oldPrice?`<span class="mold">¥${i.oldPrice}</span>`:""}</div><div class="qctrl"><button class="qb minus" onclick="updQty(${i.id},-1)"${q?"":' style="display:none"'}>−</button><span class="qnum" id="q${i.id}">${q}</span><button class="qb plus" onclick="updQty(${i.id},1)">+</button></div></div></div>`}).join("")}</div>`}).join("")}
async function updQty(id,d){if(!curRest)return;const r=curRest.id;const q=curQty[r]||{};q[id]=Math.max(0,(q[id]||0)+d);curQty[r]=q;if(q[id]<=0)delete q[id];const el=document.getElementById("q"+id);if(el){el.textContent=q[id]||0;const mb=el.parentElement.querySelector(".minus");if(mb)mb.style.display=q[id]?"":"none"}updFC();updBdg();if(token){if(d>0){await api("/cart",{method:"POST",body:JSON.stringify({restaurantId:r,menuItemId:id,quantity:1})}).catch(()=>{})}else{const ci=await api("/cart").catch(()=>[]);const f=ci.find(x=>x.menuItemId===id);if(f)await api("/cart/"+f.id,{method:"PUT",body:JSON.stringify({quantity:q[id]||0})}).catch(()=>{})}}}
function updFC(){const fc=document.getElementById("float-cart");if(!curRest){fc.style.display="none";return}const qm=curQty[curRest.id]||{};const items=curRest.menu||[];let tot=0,cnt=0;Object.entries(qm).forEach(([id,q]) => {const i=items.find(m=>m.id===parseInt(id));if(i){tot+=i.price*q;cnt+=q}});if(cnt>0){fc.style.display="flex";document.getElementById("fc-num").textContent=cnt;document.getElementById("fc-price").textContent="¥"+tot.toFixed(1);document.getElementById("fc-df").textContent=curRest.deliveryFee||0}else fc.style.display="none"}
async function updBdg(){if(!token)return;try{const items=await api("/cart");const c=items.reduce((s,v)=>s+v.quantity,0);const b=document.getElementById("badge");b.style.display=c>0?"flex":"none";if(c>0)b.textContent=c}catch{}}

// === 购物车 ===
async function loadCart(){const b=document.getElementById("cart-body");if(!token){b.innerHTML='<div class="empty"><div class="eicon">🛒</div><p>请先登录</p></div>';return}try{const items=await api("/cart");if(!items.length){b.innerHTML='<div class="empty"><div class="eicon">🛒</div><p>购物车是空的</p></div>';return}const tot=items.reduce((s,v)=>s+v.price*v.quantity,0);b.innerHTML=items.map(i=>`<div class="citem"><div class="cn">${i.name} <span style="color:#999;font-size:12px">×${i.quantity}</span></div><div class="cp">¥${(i.price*i.quantity).toFixed(1)}</div><div class="qctrl"><button class="qb minus" onclick="updCI(${i.id},-1)">−</button><span class="qnum">${i.quantity}</span><button class="qb plus" onclick="updCI(${i.id},1)">+</button></div></div>`).join("")+`<div class="ctotal"><span>合计</span><span class="tp">¥${tot.toFixed(1)}</span></div><div class="cact"><button class="clear" onclick="clearCart()">清空</button><button class="submit" onclick="goCheckout()">去结算</button></div>`}catch{b.innerHTML='<div class="empty"><p>加载失败</p></div>'}}
async function updCI(id,d){try{const items=await api("/cart");const i=items.find(x=>x.id===id);if(!i)return;const n=Math.max(0,i.quantity+d);await api("/cart/"+id,{method:"PUT",body:JSON.stringify({quantity:n})});loadCart();updBdg()}catch{}}
async function clearCart(){if(!confirm("确定清空？"))return;await api("/cart",{method:"DELETE"}).catch(()=>{});curQty={};loadCart();updBdg()}

// === 结算 ===
function goCheckout(){showPage("cart-page");setTimeout(showCheckout,400)}
async function showCheckout(){if(!token)return toast("请先登录");const items=await api("/cart").catch(()=>[]);if(!items.length)return toast("购物车为空");const r=await api("/restaurants/"+items[0].restaurantId);curRest=r;const qm={};items.forEach(i=>{qm[i.menuItemId]=i.quantity});curQty[r.id]=qm;const tot=items.reduce((s,v)=>s+v.price*v.quantity,0);const df=r.deliveryFee||3;const mb=document.getElementById("modal-body");mb.innerHTML=`<h3>${r.name}</h3>${items.map(i=>`<div class="mock-item"><span>${i.name} × ${i.quantity}</span><span>¥${(i.price*i.quantity).toFixed(1)}</span></div>`).join("")}<div class="hr"></div><div class="mock-item"><span>配送费</span><span>¥${df}</span></div><div style="margin-top:10px;text-align:right;font-size:18px;font-weight:700;color:#FF5722">合计：¥${(tot+df).toFixed(1)}</div><div style="margin-top:14px"><div class="ai"><span>📍</span><input type="text" id="ca" placeholder="送餐地址" value="${cu?.address||""}"></div><div class="ai"><span>📱</span><input type="text" id="cp" placeholder="联系电话" value="${cu?.phone||""}"></div><div class="ai"><span>📝</span><input type="text" id="cn" placeholder="备注(选填)"></div></div><div class="modal-actions"><button class="mc" onclick="closeModal()">取消</button><button class="mc3" onclick="submitOrder()">确认下单</button></div>`;document.getElementById("modal").style.display="flex"}
function closeModal(){document.getElementById("modal").style.display="none"}
async function submitOrder(){if(!token)return toast("请先登录");const r=curRest.id;const qm=curQty[r]||{};const items=curRest.menu.filter(m=>qm[m.id]);const tot=items.reduce((s,v)=>s+v.price*qm[v.id],0);try{await api("/orders",{method:"POST",body:JSON.stringify({restaurantId:r,items:items.map(i=>({id:i.id,name:i.name,price:i.price,quantity:qm[i.id]})),totalPrice:tot,deliveryFee:curRest.deliveryFee||3,address:document.getElementById("ca").value,phone:document.getElementById("cp").value,note:document.getElementById("cn").value})});curQty[r]={};closeModal();toast("下单成功！");updBdg();showPage("orders-page")}catch(e){toast(e.error||"下单失败")}}

// === 订单 ===
let otimer=null;const osm={pending:"待配送",delivering:"配送中",completed:"已完成",cancelled:"已取消"}
async function loadOrders(){const b=document.getElementById("orders-body");if(!token){b.innerHTML='<div class="empty"><p>请先登录</p></div>';return}try{const os=await api("/orders");if(!os.length){b.innerHTML='<div class="empty"><div class="eicon">📋</div><p>暂无订单</p></div>';return}b.innerHTML=os.map(o=>`<div class="ocard" onclick="showOD(${o.id})"><div class="ohead"><span class="orest">${o.restaurantName}</span><span class="ostat ${o.status}">${osm[o.status]||o.status}</span></div><div class="oitems">${(o.items||[]).map(i=>`${i.name}×${i.quantity}`).join("、")}</div><div class="obot"><span class="ototal">¥${(o.totalPrice+(o.deliveryFee||0)).toFixed(1)}</span><span class="otime">${new Date(o.createdAt+"Z").toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</span></div></div>`).join("");if(otimer)clearTimeout(otimer);otimer=setTimeout(()=>loadOrders(),5000)}catch{b.innerHTML='<div class="empty"><p>加载失败</p></div>'}}
async function showOD(id){try{const o=await api("/orders/"+id);const items=o.items||[];const mb=document.getElementById("modal-body");mb.innerHTML=`<h3>${o.restaurantName}</h3><div style="margin-bottom:10px"><span class="ostat ${o.status}">${osm[o.status]||o.status}</span><span style="font-size:12px;color:#999;margin-left:8px"> #${o.id}</span></div>${items.map(i=>`<div class="mock-item"><span>${i.name}×${i.quantity}</span><span>¥${(i.price*i.quantity).toFixed(1)}</span></div>`).join("")}<div class="hr"></div><div class="mock-item"><span>配送费</span><span>¥${o.deliveryFee}</span></div><div style="margin-top:8px;text-align:right;font-size:17px;font-weight:700;color:#FF5722">合计：¥${(o.totalPrice+(o.deliveryFee||0)).toFixed(1)}</div><div style="font-size:12px;color:#999;margin-top:8px;line-height:1.6">地址：${o.address||"未填写"}<br>电话：${o.phone||"未填写"}${o.note?"<br>备注："+o.note:""}<br>时间：${new Date(o.createdAt+"Z").toLocaleString("zh-CN")}</div><div class="modal-actions">${o.status==="pending"?`<button class="mc2" onclick="cancelOD(${o.id})">取消订单</button>`:""}${o.status==="delivering"?`<button class="mc3" onclick="completeOD(${o.id})">确认收货</button>`:""}<button class="mc" onclick="closeModal()">关闭</button></div>`;document.getElementById("modal").style.display="flex"}catch{toast("加载失败")}}
async function cancelOD(id){if(!confirm("确定取消？"))return;await api("/orders/"+id+"/cancel",{method:"PUT"}).catch(()=>{});toast("已取消");closeModal();loadOrders()}
async function completeOD(id){await api("/orders/"+id+"/complete",{method:"PUT"}).catch(()=>{});toast("已确认收货");closeModal();loadOrders()}

// === 个人中心 ===
function loadProfile(){document.getElementById("pf-name").textContent=cu?.username||"游客";document.getElementById("pf-phone").textContent=cu?.phone||"未绑定手机"}
function showAddressEdit(){const mb=document.getElementById("modal-body");mb.innerHTML=`<h3>编辑信息</h3><div class="ai"><span>👤</span><input type="text" placeholder="用户名" value="${cu?.username||""}" disabled style="opacity:.5"></div><div class="ai"><span>📍</span><input type="text" id="ea" placeholder="默认送餐地址" value="${cu?.address||""}"></div><div class="ai"><span>📱</span><input type="text" id="ep" placeholder="联系电话" value="${cu?.phone||""}"></div><div class="modal-actions"><button class="mc" onclick="closeModal()">取消</button><button class="mc3" onclick="savePf()">保存</button></div>`;document.getElementById("modal").style.display="flex"}
async function savePf(){const a=document.getElementById("ea").value;const p=document.getElementById("ep").value;await api("/auth/me",{method:"PUT",body:JSON.stringify({address:a,phone:p})}).catch(()=>{});cu.address=a;cu.phone=p;closeModal();toast("保存成功");loadProfile()}

// === 搜索 ===
async function doSearch(k){const sr=document.getElementById("sr");if(!k.trim()){sr.innerHTML='<div class="empty">🔍<p>搜索你喜欢的餐厅和美食</p></div>';return}const d=await api("/restaurants?keyword="+encodeURIComponent(k));if(!d.length){sr.innerHTML='<div class="empty">😕<p>未找到相关结果</p></div>';return}renderR(d,sr)}

// === 初始化 ===
(async function init(){if(token){try{cu=await api("/auth/me");document.getElementById("page-auth").classList.remove("active");document.getElementById("page-home").classList.add("active");showPage("home");return}catch{token="";localStorage.removeItem("token")}}document.getElementById("page-auth").classList.add("active");switchAuth(1)})();